config/routes.rb
SampleApp::Application.routes.draw do
  
  get "relationships/create"

  get "relationships/destroy"

  get "sessions/new"

  root :to => 'pages#home'  # || match '/', :to => '#pages#home'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :commentaires

  match '/home', :to => 'pages#home'
  match 'contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/users/:id/mescommentaires', :to => 'commentaires#mes_commentaires'
  match '/:categorie_nom', :to => 'microposts#post_par_categorie'


end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "erreur") %>    <!== met au pluriel en fonction du nombre en param==>
        ont empêché d'enregistrer votre inscription</h2>
    <p>Merci de corriger ces champs :</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feedList.html.erb
<% if !@feedList.empty?  %>
  <h3>Post de vos auteurs suivis: </h3>
   <% @feedList.each do |micropost| %>
   		<%= render micropost %>
   <% end %>
<% else %>
         <h3> Pas de post pour le moment. </h3>
<% end %>

app/views/shared/_micropost_form.erb
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_field :content, :size => 100 %>
  </div>
  <table>
  	<tr>
  		<% Categorie.all.each do |categorie| %>
  			<td>
  				<%= f.radio_button :categorie_id, "#{categorie.id}"%>
          <%= f.label "#{categorie.nom}" %>
  			</td>
  		<% end %>
  	</tr>
  </table>
  <div class="actions">
    <%= f.submit "Soumettre" %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
          <%= pluralize(@user.following.count, "auteur suivi", "auteurs suivis") %>
          </span> 
        </a> |
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "lecteur") %>
          </span> 
        </a> 
      </td>
       <% if current_user.id == @user.id %> 
        <td>
        |  <%= link_to "Mes commentaires" , "#{@user.id}/mescommentaires" %>
        </td>
       <% elsif current_user.admin? %> 
        <td>
        |  <%= link_to "Ses commentaires" , "#{@user.id}/mescommentaires" %>
        </td>
       <% end %>
    </tr>
  </table>
</div>

app/views/shared/_user_info.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <span class="user_name">
      <%= current_user.nom %>
    </span>
    <br/>
    <span class="microposts">
      <%= pluralize(current_user.microposts.count, "messages") %>
    </span>
  </a>
</div>