config/routes.rb
SampleApp::Application.routes.draw do
  
  get "relationships/create"

  get "relationships/destroy"

  get "sessions/new"

  root :to => 'pages#home'  # || match '/', :to => '#pages#home'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :commentaires

  match '/home', :to => 'pages#home'
  match 'contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/users/:id/mescommentaires', :to => 'commentaires#mes_commentaires'
  match '/:categorie_nom', :to => 'microposts#post_par_categorie'


end

app/views/pages/about.html.erb
<h1>Bienvenue sur la page <%= @titre %></h1>

<a href="http://localhost:3000/">Localhost</a>

app/views/pages/contact.html.erb
<h1>Bienvenue sur la page <%= @titre %></h1>

<%= link_to "Accueil", root_path %>

app/views/pages/help.html.erb
<h1>Bienvenue sur la page <%= @titre %></h1>

<%= link_to "Accueil", root_path %>

app/views/pages/home.html.erb
<% if signed_in? %>
  <table class="front" summary="Pour visiteur identifié">
    <tr>
      <td class="main">
        <h1 class="micropost">Quoi de neuf ?</h1>
        <%= render 'shared/micropost_form' %>
      </td>
      <td class="sidebar round">
        <%= render 'shared/user_info' %>
        <%= render 'shared/stats' %>
      </td>
    </tr>
    <tr>
      <td>
        <%= render "shared/feedList" %>
      </td>
    </tr>
  </table>
<% else %>
	<table class="table">
	<tr>
		<td><%= link_to "Se connecter!", signin_path, :class => "signup_button round" %></td>
		<td><%= link_to "S'inscrire!", signup_path, :class => "signup_button round" %></td>
	</tr>
	</table>
<% end %>

app/views/pages/inscription.html.erb
<h1>Bienvenue sur la page <%= @titre %></h1>

<%= link_to "Accueil", root_path %>