config/routes.rb
SampleApp::Application.routes.draw do
  
  get "relationships/create"

  get "relationships/destroy"

  get "sessions/new"

  root :to => 'pages#home'  # || match '/', :to => '#pages#home'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :commentaires

  match '/home', :to => 'pages#home'
  match 'contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/users/:id/mescommentaires', :to => 'commentaires#mes_commentaires'
  match '/:categorie_nom', :to => 'microposts#post_par_categorie'


end

app/models/micropost.rb
# == Schema Information
#
# Table name: microposts
#
#  id           :integer          not null, primary key
#  content      :string(255)
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  categorie_id :integer
#

class Micropost < ActiveRecord::Base
  attr_accessible :content, :categorie_id

  belongs_to :user
  has_many :commentaires, :dependent => :destroy

  default_scope :order => "microposts.created_at DESC"

  validates :user_id, :presence => true
  validates :content, :presence => true,
  					  :length => { :maximum => 150 }
  validates :categorie_id, :presence => true

  def self.from_users_followed_by(user)
    followed_ids = user.following.map(&:id).join(", ")
    where("user_id IN (?) OR user_id = ?", followed_ids, user.id)
  end

  def self.micropost_par_cat(categorie)
    where("categorie_id = ?", categorie.id)
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

    before_filter :authenticate
    before_filter :authorized_user, :only => :destroy

  def create
  	@micropost = current_user.microposts.build(params[:micropost])
    puts "ID CAT #{@micropost.categorie_id}"
  	if @micropost.save
  		flash[:success] = "Micropost cree"
  		redirect_to root_path
 	  else
 		  @feedList = []
 		  flash.now[:error] = "Oups! Pas cree"
 		  render "pages/home"
 	  end
  end

  def destroy
  	@micropost.destroy
  	flash[:success] = "Post supprime!"
  	redirect_to root_path
  end

  def post_par_categorie
    @categorie = Categorie.find_by_nom(params[:categorie_nom])
    @titre = "#{@categorie.nom}"
    @microposts = Micropost.micropost_par_cat(@categorie)

  end

  private
  	def authorized_user
  		@micropost = current_user.microposts.find(params[:id])
  		redirect_to root_path if @micropost.nil?
  	end
end

app/helpers/micropost_helper.rb
module MicropostHelper
end

app/views/microposts/_micropost.html.erb
		<li><p>
			  <strong>" <%= micropost.content %> "</strong>
			  <% categorie = Categorie.find(micropost.categorie_id) %>
			  <% user = User.find_by_id(micropost.user_id) %>
     		  Posté il y a <%= time_ago_in_words(micropost.created_at) %> par 
     		  <% if current_user.id == micropost.user_id %>
     		  	<%= link_to "Vous", user %>
    	 	  <% else %>
    	 	  	<%= link_to "#{user.nom}", user %>
    	 	  <% end %>
    	 	  <br/>
    	 	  Les autres posts de <%= link_to "#{categorie.nom}", "/#{categorie.nom}" %>
    	 	</p>
    	 	<div class="boutMicropost">
	    	  <% if micropost.user_id == current_user.id || current_user.admin? %>
	    	 	<%= link_to "Delete", micropost, :method => :delete, 
	     										 :confirm => "Supprimer votre post?", 
	     										 :title => "Supprimer micropost" %> 
	     	  <% end %>
	     	  <%= link_to "Les commenaires (#{micropost.commentaires.count})", commentaires_path(:micropost_id => micropost.id) %>
	     	  <%= link_to "Commenter", new_commentaire_path(:micropost_id => micropost.id) %>
	     	</div>
		</li>

app/views/microposts/post_par_categorie.html.erb
<h3>Posts de la catégorie <%= @categorie.nom %></h3>
<% if @microposts.any? %>
	<ul>
		<% @microposts.each do |post| %>
			<%= render post %>
		<% end %>
	</ul>
<% else %>
	<h5>Il n'y a pas encore de post pour cette catégorie</h5>
	<%= link_to "Laisser un post?", root_path %>
<% end %>