config/routes.rb
SampleApp::Application.routes.draw do
  
  get "relationships/create"

  get "relationships/destroy"

  get "sessions/new"

  root :to => 'pages#home'  # || match '/', :to => '#pages#home'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :commentaires

  match '/home', :to => 'pages#home'
  match 'contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/users/:id/mescommentaires', :to => 'commentaires#mes_commentaires'
  match '/:categorie_nom', :to => 'microposts#post_par_categorie'


end

app/views/layouts/_footer.html.erb
<footer>
  <%= yield :scripts %>
  <nav class="round">
    <ul>
      <li><%= link_to "À Propos", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Tutoriel Rails</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_googleMapsApi.html.erb
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyAZiDoed7v6rc5lXXH2h3gt9-pvC3hKwwY&sensor=false" %> 
<%= javascript_include_tag "googleMapsApi" %>
<% #<script type="text/javascript" %>

app/views/layouts/_header.html.erb
<header>
    <%= link_to logo, root_path %>
    <nav class="round">
       <ul>
         <li><%= link_to "Accueil", root_path %></li>
         <% if signed_in? %>
         	<li><%= link_to "Mon profil", current_user %>
          <li><%= link_to "Utilisateurs", users_path %></li>
         	<li><%= link_to "Se deconnecter", signout_path, :method => :delete %></li>
         <% else %>
         	<li><%= link_to "S'identfier", signin_path %></li>
       	 <% end %>
       	 <li><%= link_to "Aide", help_path %></li>
       </ul>
    </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'monStyle', :media => 'all' %>
<%= stylesheet_link_tag 'gmaps4rails', :media => 'all' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= titre %></title>
    <%= csrf_meta_tag %>   
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag "application" %> 
    <%= render 'layouts/googleMapsApi' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>